### ISSUE TITLE
Spreadsheet - SupportAllDrives and Find File By ID

### ISSUE THREAD

**Issue by alecfletcher349** [greenmtnboy/pygsuite#30]
Could we add supportAllDrives functionality to find_files in drive_object.py?

Similarly, could we allow for searching by file_id, instead of name, if needed? 

This worked for me: 

```
def find_files(self, type: FileTypes, name: Optional[str] = None, file_id: Optional[str] = None, supportsAllDrives = False):
    q = f'mimeType="{type}"'
    if name:
        q += f' and name = "{name}"'
        base = self.service.files().list(q=q, supportsAllDrives=supportsAllDrives, includeItemsFromAllDrives=supportsAllDrives).execute()
        files = base.get("files")
        page_token = base.get("nextPageToken")
        while page_token is not None:
            base = self.service.files().list(q=q, page_token=page_token, supportsAllDrives=supportsAllDrives, includeItemsFromAllDrives=supportsAllDrives).execute()
            files += base.get("files")
            page_token = base.get("nextPageToken")
        return files
    if id: 
        files = self.service.files().get(fileId=file_id, supportsAllDrives=supportsAllDrives).execute()
        return files
```

**Comment by samgaudet** [comment]
Hey Alec, this is a great suggestion! On top of that, your timing fits well with some changes I have had in progress for sometime ([PR here](https://github.com/greenmtnboy/pygsuite/pull/25)).

In that PR, you'll see some updates to the `find_files` method, including the support for `support_all_drives` like you mentioned. This PR still needs a bit of work, especially around documentation, as well as a thorough code review. You can preview what this new functionality will look like in [this example file I put together for the use case](https://github.com/greenmtnboy/pygsuite/blob/sgaudet_drive/examples/use_cases/find_files_in_drive.py).

In addition, I will look into the best implementation for searching by file ID&mdash;with this PR, you will already be able to create a new `File` object by ID, so that will not be too much to add here.

Please feel free to leave any additional feedback about how the functionality looks, and I'll be sure to reach out about some user testing once these changes are deployed!
